"""empty message

Revision ID: 7820577d7a76
Revises: 0001_initial
Create Date: 2026-04-10 23:43:13.469024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7820577d7a76'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_owner_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_priority'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['owner_user_id'], ['id'])
    op.drop_index(op.f('ix_task_tag_is_primary'), table_name='task_tag')
    op.drop_index(op.f('ix_task_tag_tag_id'), table_name='task_tag')
    op.drop_index(op.f('ix_task_tag_task_id'), table_name='task_tag')
    op.drop_constraint(op.f('uq_task_tag'), 'task_tag', type_='unique')
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.create_foreign_key(None, 'task_tag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'task_tag', 'task', ['task_id'], ['id'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_task_assignment_task_id'), table_name='user_task_assignment')
    op.drop_index(op.f('ix_user_task_assignment_user_id'), table_name='user_task_assignment')
    op.drop_constraint(op.f('uq_user_task'), 'user_task_assignment', type_='unique')
    op.drop_constraint(None, 'user_task_assignment', type_='foreignkey')
    op.drop_constraint(None, 'user_task_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'user_task_assignment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_task_assignment', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task_assignment', type_='foreignkey')
    op.drop_constraint(None, 'user_task_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'user_task_assignment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_task_assignment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_task'), 'user_task_assignment', ['user_id', 'task_id'])
    op.create_index(op.f('ix_user_task_assignment_user_id'), 'user_task_assignment', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_task_assignment_task_id'), 'user_task_assignment', ['task_id'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.create_foreign_key(None, 'task_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_tag', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_task_tag'), 'task_tag', ['task_id', 'tag_id'])
    op.create_index(op.f('ix_task_tag_task_id'), 'task_tag', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_tag_tag_id'), 'task_tag', ['tag_id'], unique=False)
    op.create_index(op.f('ix_task_tag_is_primary'), 'task_tag', ['is_primary'], unique=False)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_priority'), 'task', ['priority'], unique=False)
    op.create_index(op.f('ix_task_owner_user_id'), 'task', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###
